#!/bin/bash

echo "Set hostname to emonpi"
sudo sed -i 's/raspberrypi/emonpi/' /etc/hosts
sudo sed -i 's/raspberrypi/emonpi/' /etc/hostname

echo "disable serial console"
sudo wget https://raw.githubusercontent.com/lurch/rpi-serial-console/master/rpi-serial-console -O /usr/bin/rpi-serial-console && sudo chmod +x /usr/bin/rpi-serial-console
sudo rpi-serial-console disable

echo "enable serial uploads with avrdue and autoreset & install minicom"
git clone https://github.com/openenergymonitor/avrdude-rpi.git ~/avrdude-rpi && ~/avrdude-rpi/install

echo "install ino Arduino compile tool"
sudo apt-get install arduino -f
sudo apt-get install python-pip
pip install ino

echo "disable the raspi-config auto run"
sudo rm /etc/profile.d/raspi-config.sh

echo "clone emonpi github"
git clone https://github.com/openenergymonitor/emonpi.git ~/emonpi  

echo "install shutdown service"
sudo /home/pi/emonpi/shutdownpi/install

echo "install LCD"
sudo /home/pi/emonpi/lcd/install



