#!/bin/bash

echo
echo "================================="
echo "Emoncms update started"
echo

date

echo

cd /var/www/emoncms
git pull origin low-write

cd /var/www/emoncms/Modules/nodes
git pull origin master

cd /var/www/emoncms/Modules/app
git pull origin master

cd /var/www/emoncms/Modules/config
git pull origin master

cd /var/www/emoncms/Modules/wifi
git pull origin master

cd /home/pi/emonhub
git pull origin emon-pi

if ! grep -q "V2.x_emonTH_DHT22_DS18B20_RFM69CW_Pulse" /home/pi/data/emonhub.conf ; then
  echo "Appending emonTH V2.x pulse counting node decoding additions to /home/pi/data/emonhub.conf..."
  echo -e "$(</home/pi/emonpi/emonhub.conf_emonTHaddition)" >> /home/pi/data/emonhub.conf
  echo "..Done"
else
  echo "emonTH V2.x pulse counting node decoding additions already appened to /home/pi/data/emonhub.conf"
fi

sudo service emonhub restart
sudo service emoncms-nodes-service restart
sudo service feedwriter restart

sudo service emonPiLCD restart

echo
echo "Emoncms update finished"
echo "================================="
echo
