#!/bin/bash
echo
echo "================================="
echo "EmonPi update started"
echo "================================="
echo
echo "EUID: $EUID"
echo

# Needed for emonPi LCD Hi-Link 3G dongle support
# ALLREADY INSTALLED
# sudo pip install xmltodict
# sudo pip install requests
sudo pip install paho-mqtt --upgrade

# Ensure rpi gpio is latest version and gpiozero is installed, required for V2.2.0 LCD script
sudo apt-get update
sudo apt-get install python-gpiozero python-rpi.gpio -y

sudo /etc/init.d/emonhub stop

echo "Start ATmega328 serial upload using avrdude with latest.hex"

# Discrete Sampling
echo "Discrete Sampling"
echo "avrdude -c arduino -p ATMEGA328P -P /dev/ttyAMA0 -b 115200 -U flash:w:/home/pi/emonpi/firmware/compiled/latest.hex"
avrdude -c arduino -p ATMEGA328P -P /dev/ttyAMA0 -b 115200 -U flash:w:/home/pi/emonpi/firmware/compiled/latest.hex

# RFM12Pi with RFM12B update
# avrdude -v -c arduino -p ATMEGA328P -P /dev/ttyAMA0 -b 38400 -U flash:w:/home/pi/RFM2Pi/firmware/RFM69CW_RF_Demo_ATmega328/RFM12_Demo_ATmega328.cpp.hex

# RFM69Pi with RFM69CW Update
# avrdude -v -c arduino -p ATMEGA328P -P /dev/ttyAMA0 -b 38400 -U flash:w:/home/pi/RFM2Pi/firmware/RFM69CW_RF_Demo_ATmega328/RFM69CW_RF12_Demo_ATmega328.cpp.hex

sudo /etc/init.d/emonhub start

#########################################################################################################

# Move ~/.npm folder to RW folder ~/data/npm to allow npm packages to be installed when emonPi is in RO mode

#if [ ! -d /home/pi/data/npm ]; then
#  echo "moving ~./npm to ~/data/npm and create symlink"
#  mv /home/pi/.npm /home/pi/data/npm
#  ln -s /home/pi/data/npm /home/pi/.npm
#fi

#########################################################################################################

# Install / update nodeRED  emonPixel & Emoncms nodes

#cd /home/pi/.node-red
##npm install https://github.com/openenergymonitor/node-red-contrib-emonpixel
#npm install node-red-node-emoncms
#cd /home/pi
