#!/bin/bash
echo
echo "================================="
echo "EmonPi update started"
echo "================================="

sudo service emonhub stop
sudo service emonPiLCD stop


avrdude -v -c arduino -p ATMEGA328P -P /dev/ttyAMA0 -b 115200 -U flash:w:/home/pi/emonpi/Atmega328/emonPi_RFM69CW_RF12Demo_DiscreteSampling/compiled/emonPi_latest.hex
