#!/bin/bash

echo
echo "================================="
echo "Emoncms update started"
echo

date

echo

echo "git pull /var/www/emoncms"
cd /var/www/emoncms
git branch
git pull

echo

if [ -d /var/www/emoncms/Modules/nodes ]; then
  echo "git pull /var/www/emoncms/Modules/nodes"
  cd /var/www/emoncms/Modules/nodes
  git branch
  git pull
fi

echo

echo "git pull /var/www/emoncms/Modules/app"
cd /var/www/emoncms/Modules/app
git branch
git pull

echo

echo "git pull /var/www/emoncms/Modules/config"
cd /var/www/emoncms/Modules/config
git branch
git pull

echo

echo "git pull /var/www/emoncms/Modules/wifi"
cd /var/www/emoncms/Modules/wifi
git branch
git pull

echo "git pull /var/www/emoncms/Modules/dashboard"
cd /var/www/emoncms/Modules/dashboard
git branch
git pull

echo

echo "Copy new default.emonpi.settings.php to settings.php & make backup old.emonpi.settings.php"
sudo cp /var/www/emoncms/settings.php /var/www/emoncms/old.settings.php
sudo cp /var/www/emoncms/default.emonpi.settings.php /var/www/emoncms/settings.php

echo

sudo /etc/init.d/emonhub restart
sudo /etc/init.d/feedwriter restart

if [ -f /etc/init.d/emoncms-nodes-service ]; then
  sudo /etc/init.d/emoncms-nodes-service restart
fi

if [ -f /etc/init.d/openhab ]; then
  sudo /etc/init.d/openhab restart
fi

if [ -f /etc/init.d/mqtt_input ]; then
  sudo /etc/init.d/mqtt_input start
  sleep 1
  sudo /etc/init.d/mqtt_input restart
fi



echo
echo "Emoncms update finished"
echo "================================="
echo
