#!/bin/bash

echo "Factory reset"

sudo service emonhub stop
sudo service emoncms-nodes-service stop
sudo service feedwriter stop

sudo service redis-server restart

echo "emoncms.conf reset"
cd /home/pi
> emoncms.conf
sudo mv /home/pi/emoncms.conf /home/pi/data/emoncms.conf
sudo chown pi:www-data /home/pi/data/emoncms.conf
sudo chmod 664 /home/pi/data/emoncms.conf

echo "emonhub.conf reset"
sudo cp /home/pi/emonhub/conf/emonhub.conf /home/pi/data/emonhub.conf
sudo chown pi:www-data /home/pi/data/emonhub.conf
sudo chmod 664 /home/pi/data/emonhub.conf

echo "deleting phpfina and phptimeseries data"
sudo rm -rf /home/pi/data/phpfina
sudo rm -rf /home/pi/data/phptimeseries

echo "creating new phpfina and phptimeseries folders"
sudo mkdir /home/pi/data/phpfina
sudo mkdir /home/pi/data/phptimeseries
sudo chown www-data:root /home/pi/data/phpfina
sudo chown www-data:root /home/pi/data/phptimeseries

echo "deleting mysql emoncms database"
mysql -u root -e "drop database emoncms" -praspberry

echo "creating new mysql emoncms database"
mysql -u root -e "create database emoncms" -praspberry

sudo service emonhub start
sudo service emoncms-nodes-service start
sudo service feedwriter start
