#!/bin/bash

echo "deleting unused software"
sudo apt-get purge -y wolfram-engine minecraft-pi sonic-pi scratch
sudo apt-get autoremove -y
sudo apt-get clean

echo "Set hostname to emonpi"
sudo sed -i 's/raspberrypi/emonpi/' /etc/hosts
sudo sed -i 's/raspberrypi/emonpi/' /etc/hostname


echo "enable serial uploads with avrdue and autoreset & install minicom & enable use of serial port"
git clone https://github.com/openenergymonitor/avrdude-rpi.git ~/avrdude-rpi && ~/avrdude-rpi/install

echo "install ino Arduino compile tool"
sudo apt-get install arduino -y
sudo apt-get install python-pip
pip install ino

echo "disable the raspi-config auto run"
sudo rm /etc/profile.d/raspi-config.sh

# Only used when emonPi is used without LCD, run either LCD service or shutdwn service. LCD script also handles shutdown 
# echo "install shutdown service"
# sudo /home/pi/emonpi/shutdownpi/install

echo "install LCD"
sudo /home/pi/emonpi/lcd/install



