#!/bin/bash

sudo ln ~/emonpi/shutdownpi/shutdownpi /usr/bin/shutdownpi
sudo ln ~/emonpi/shutdownpi/shutdownpi.sh /etc/init.d/shutdownpi.sh
sudo update-rc.d shutdownpi.sh defaults
sudo service shutdownpi start 

