#!/bin/bash

echo "update"
sudo apt-get update -y
sudo apt-get upgrade -y

echo "deleting unused software"
sudo apt-get purge -y wolfram-engine minecraft-pi sonic-pi scratch
sudo apt-get autoremove -y
sudo apt-get clean

echo "Set hostname to emonpi"
sudo sed -i 's/beaglebone/emonpi/' /etc/hosts
sudo sed -i 's/beaglebone/emonpi/' /etc/hostname


echo "enable serial uploads with avrdue and autoreset & install minicom & enable use of serial port"
git clone https://github.com/openenergymonitor/avrdude-rpi.git ~/avrdude-rpi && ~/avrdude-rpi/install

#echo "install ino Arduino compile tool"
#sudo apt-get install arduino -y
#sudo apt-get install python-pip -y
#pip install ino

#echo "disable the raspi-config auto run"
#sudo rm /etc/profile.d/raspi-config.sh

# Only used when emonPi is used without LCD, run either LCD service or shutdwn service. LCD script also handles shutdown 
# echo "install shutdown service"
# sudo /home/pi/emonpi/shutdownpi/install

echo "install LCD"
sudo /home/debian/emonpi/lcd/install

echo "move /etc/resolv.conf to RW data partition to allow updating of DNS nameservers"
# create sim link of resolv.conf and resolv.conf.dhclient-new in RW /data to /etc
cp /etc/resolv.conf /home/debian/data/
sudo rm /etc/resolv.conf 
sudo ln -s /home/debian/data/resolv.conf /etc/resolv.conf

# Create resolv.conf.dhclient-new file and symlink to /etc
touch /home/debian/data/resolv.conf.dhclient-new
sudo ln -s /home/debian/data/resolv.conf.dhclient-new /etc/resolv.conf.dhclient-new

# make backup of  dhclient-script
sudo cp /sbin/dhclient-script /sbin/dhclient-script_original

# Best do these steps manually: https://github.com/openenergymonitor/emonpi/blob/master/imagebuild.md
#echo "Move log directory to temporary partition"
#sudo cp /etc/default/rcS /etc/default/rcS.orig
#sudo sh -c "echo 'RAMTMP=yes' >> /etc/default/rcS"

#echo "setup /etc/fstab to make file system read-only be default"
#sudo mv /etc/fstab /etc/fstab.orig
#sudo sh -c "echo 'tmpfs           /tmp            tmpfs   nodev,nosuid,size=30M,mode=1777       0    0' >> /etc/fstab"
#sudo sh -c "echo 'tmpfs           /var/log        tmpfs   nodev,nosuid,size=30M,mode=1777       0    0' >> /etc/fstab"
#sudo sh -c "echo 'proc            /proc           proc    defaults                              0    0' >> /etc/fstab"
#sudo sh -c "echo '/dev/mmcblk0p1  /boot           vfat    defaults                              0    2' >> /etc/fstab"
#sudo sh -c "echo '/dev/mmcblk0p2  /               ext4    defaults,noatime                      0    1' >> /etc/fstab"
#sudo sh -c "echo ' ' >> /etc/fstab"
#sudo mv /etc/mtab /etc/mtab.orig
#sudo ln -s /proc/self/mounts /etc/mtab

# copy modified dhclient-script
sudo cp /home/debian/emonpi/dhclient-script /sbin/dhclient-script

