#!/bin/bash
echo
echo "================================="
echo "EmonPi new firmware started"
echo "================================="

sudo service emonhub stop
sudo service emonPiLCD stop

echo "Start ATmega328 serial upload using avrdude "
if [ -f /usr/bin/autoreset ]
then
        echo "System is changing autoreset pin"
        echo "adding autoreset pin"
		#bbb pin P9_15 to the reset pin of emonTx
        sudo  sed -i "s/7/'P9_15'/g" /usr/bin/autoreset
        sudo sed -i "s/RPI.GPIO/Adafruit_BBIO.GPIO/g" /usr/bin/autoreset
        sudo sed -i "s/GPIO.setmode(GPIO.BOARD)/#GPIO.setmode(GPIO.BOARD)/g" /usr/bin/autoreset
        # emonPi/emonTxBase ATmega328 update
avrdude -v -c arduino -p ATMEGA328P -P /dev/ttyO2 -b 115200  -U flash:w:/home/RMC/emonpi/Atmega328/emonPi_RFM69CW_RF12Demo_DiscreteSampling/emonPi_RFM69CW_RF12Demo_DiscreteSampling.cpp.hex


else

         echo "Autoreset file does not exist"
fi