#!/bin/bash

sudo cp ~/emonpi/shutdownpi/shutdownpi /usr/bin/shutdownpi
sudo ln ~/emonpi/shutdownpi/shutdownpi /usr/bin/shutdownpi
sudo chmod a+x /usr/bin/shutdownpi
sudo cp ~/emonpi/shutdownpi/shutdownpi.sh /etc/init.d
sudo ln ~/emonpi/shutdownpi/shutdownpi.sh /etc/init.d
sudo update-rc.d shutdownpi.sh defaults
sudo service shutdownpi start 

