#!/bin/bash

## Used to update log viewer window in Emoncms admin
# Used in conjunction with: service-runner-update.sh and Emoncms admin module 

scriptname=$(basename $0)
pidfile="/tmp/${scriptname}"

# lock it
exec 200>$pidfile
flock -n 200 || exit 1
pid=$$
echo $pid 1>&200

echo "starting service-runner"

while :
do
    flag=$(redis-cli lpop service-runner)
    if [ "$flag" ]; then
        echo "flag: "$flag
        IFS=\> read script logfile <<< "$flag"
        echo "STARTING: $script > $logfile"
        $script > $logfile
        if [ ! -e $logfile ]; then
            touch $logfile
        fi
        echo "COMPLETE: $script > $logfile"
    fi

    sleep 1
done
