#!/bin/bash

LOCK=/tmp/updatelock
if [ -f $LOCK ]; then
  echo Job is already running\!
  exit 6
fi
touch $LOCK

if [ ! -f /tmp/emonpiupdate ]; then
    exit
fi

rpi-rw

cd /home/pi/emonpi
git pull

/home/pi/emonpi/emonpiupdate
/home/pi/emonpi/emoncmsupdate

sudo rm /tmp/emonpiupdate

rpi-ro

rm $LOCK
