#!/bin/bash

if [ ! -f /tmp/emonpiupdate ]; then
    exit
fi

LOCK=/tmp/updatelock
if [ -f $LOCK ]; then
  echo Job is already running\!
  exit 6
fi
touch $LOCK

rpi-rw

cat /dev/null >  /var/log/emonpiupdate.log 

cd /home/pi/emonpi
git checkout master
git pull origin master

/home/pi/emonpi/emonpiupdate
/home/pi/emonpi/emoncmsupdate

sudo rm /tmp/emonpiupdate

rpi-ro

rm $LOCK
