#!/bin/bash

# If update flag does not exit then exit
if [ ! -f /tmp/emonpiupdate ]; then
    exit
fi

LOCK=/tmp/updatelock
if [ -f $LOCK ]; then
  echo Job is already running\!
  exit 6
fi
touch $LOCK

# Make FS RW
rpi-rw

# Clear log update file
cat /dev/null >  /home/pi/data/emonpiupdate.log

# Stop emonPi LCD servcice
sudo service emonPiLCD stop

# Display update message on LCD
sudo /home/pi/emonpi/lcd/./emonPiLCD_update.py &


echo "Starting emonPi Update >"
echo
# Date and time
date
echo

echo "Update emonPi git:"
cd /home/pi/emonpi
git pull
echo
echo "Start emonPi Atmega328 firmware update:"
# Run emonPi update script to update firmware on Atmega328 on emonPi Shield using avrdude
/home/pi/emonpi/emonpiupdate
echo

echo "Start emoncms update:"
# Run emoncms update script to pull in latest emoncms & emonhub updates  
/home/pi/emonpi/emoncmsupdate
echo

echo
sudo /etc/init.d/emonPiLCD start



# Remove update flag now update has finished 
sudo rm /tmp/emonpiupdate

printf "\n...................\n"
printf "emonPi update done\n"
date
echo

rm $LOCK

# Put file system back into read-only
rpi-ro


