#!/bin/bash

# Run script as root $ sudo ./install

echo "Enable I2C module"

#i2c0: Not exposed in the expansion headers
#i2c1: pins P9 17,18 (and 24,26)
#i2c2: pins P9 19,20 (and 21,22)

#---------GPRR signal strength file------
sudo cp /home/debian/emonpi/gprs/gprs_signal.py /home/debian/emonpi/lcd/gprs_signal.py

cd /sys/devices/bone_capemgr.9/
file=slots

i2c_ports=`grep -c "BB-I2C1" "$file"`

if [ $i2c_ports -eq 1 ]
then
        echo "I2C 2 is already enabled"
else
        echo "i2c 2 is enabled"
        sudo echo BB-I2C1 >> /sys/devices/bone_capemgr.9/slots

fi
#---------------------------------------------------------------------------------------------
echo "Enable I2C on boot"

sudo touch /root/tempcrontab.txt
cd /root/
file=tempcrontab.txt

i2c_on_boot=`grep -c "@reboot sudo echo BB-I2C1 >> /sys/devices/bone_capemgr.9/slots" "$file"`


#enable i2c to be enabled on boot
if [ $i2c_on_boot -eq 1 ]
then

        echo "Code line exist"
        crontab -l >tempcrontab.txt
        #sudo echo '@reboot sudo echo BB-I2C1 >> /sys/devices/bone_capemgr.9/slots' >> /root/tempcrontab.txt
        sudo echo '@reboot sh /home/debian/emonpi/gprs/enable_ttyo4.sh' >> /root/tempcrontab.txt
	sudo echo '@reboot sh /home/debian/emonpi/usb_reset.sh' >> /root/tempcrontab.txt
        crontab tempcrontab.txt
else
        echo "Adding the code line....."
        crontab -l >tempcrontab.txt
        sudo echo '@reboot sudo echo BB-I2C1 >> /sys/devices/bone_capemgr.9/slots' >> /root/tempcrontab.txt
        sudo echo '@reboot sh /home/debian/gprs/enable_ttyo4.sh' >> /root/tempcrontab.txt
	sudo echo '@reboot sh /home/debian/emonpi/usb_reset.sh' >> /root/tempcrontab.txt
        crontab tempcrontab.txt

fi



#---------------------------------------------------------------------------------------------------
echo 'Install Python I2C Tools'
sudo apt-get install python-smbus i2c-tools -y

echo 'Attemp to search for LCD I2C address:'
# Use port 2 for bbb
#sudo i2cdetect -r 2

echo 'I2C for LCD is enabled; reboot to take effect'

echo 'Install emonPi Python LCD install scripts'
if [ -f /etc/init.d/emonPiLCD ]
then
	echo "/etc/init.d/emonPiLCD already exists doing nothing"
else
	echo "copying daemon script /etc/init.d/emonPiLCD"
	sudo cp /home/debian/emonpi/lcd/emonPiLCD /etc/init.d/emonPiLCD
	echo "updating rc scripts for auto-start"
	sudo update-rc.d emonPiLCD start
	echo "updating rc scripts to enable start"
	sudo update-rc.d emonPiLCD enable
fi


echo "Starting LCD script"
sudo service emonPiLCD start

echo 'I2C LCD installed...please reboot to take effect'

if [ -f /etc/init.d/emonPiLCD ]
then
	echo "/etc/init.d/emonPiLCD akready exists doing nothing"
else
	echo "copying daemon script /etc/init.d/emonPiLCD"
	sudo cp /home/debian/emonpi/lcd/emonPiLCD /etc/init.d/emonPiLCD
	echo "updating rc scripts for auto-start"
	sudo update-rc.d emonPiLCD start
	echo "updating rc scripts to enable start"
	sudo update-rc.d emonPiLCD enable
fi
echo "Starting LCD script"
sudo service emonPiLCD start
echo 'I2C LCD installed...please reboot to take effect'
