#!/bin/bash

# Run script as root $ sudo ./install 
# Reboot required for I2C  enable to take effect

# emonPi - Raspberry Pi Energy Monitoring 
# Part of the OpenEnergyMonitor.org project 

echo 'Install Python pip, Python I2C Tools and uptime module'
sudo apt-get update
sudo apt-get install python-smbus i2c-tools python-rpi.gpio python-pip redis-server -y
sudo pip install uptime
sudo pip install redis
sudo pip install paho-mqtt

echo "Enable I2C module" 

# Black list method is not used in newer versions of Raspbien 
#if ! grep -Fxq "#blacklist i2c-bcm2708" /etc/modprobe.d/raspi-blacklist.conf ; then
#	sudo sed -i 's/blacklist i2c-bcm2708/#blacklist i2c-bcm2708/' /etc/modprobe.d/raspi-blacklist.conf
#	echo 'I2C module enabled in /etc/modprobe.d/raspi-blacklist.conf'
#else
#	echo 'I2C already enabled in /etc/modprobe.d/raspi-blacklist.conf'
#fi

if ! grep -Fxq "i2c-bcm2708" /etc/ ; then
	sudo echo 'i2c-bcm2708' >> /etc/
	echo 'i2c-bcm2708 enabled in /etc/'
else
	echo 'i2c-bcm2708 already enabled in /etc/'
fi


if ! grep -Fxq "i2c-dev" /etc/ ; then
	sudo echo 'i2c-dev' >> /etc/
	echo 'i2c-dev enabled in /etc/'
else
	echo 'i2c-dev already enabled in /etc/'
fi

if ! grep -Fxq "dtparam=i2c_arm=on" /boot/config.txt ; then
	sudo echo 'dtparam=i2c_arm=on' >> //boot/config.txt
	echo 'tparam=i2c_arm=on added to /boot/config.txt'
else
	echo 'tparam=i2c_arm=on already added to /boot/config.txt'
fi


# create linked directoty for LCD scripts 
sudo rm -r /usr/share/emonPiLCD
sudo ln -s /home/pi/emonpi/lcd/ /usr/share/emonPiLCD

# create linked init service script 
sudo rm -f /etc/init.d/emonPiLCD
sudo ln -s /home/pi/emonpi/lcd/emonPiLCD /etc/init.d/emonPiLCD

# launch at startup 
sudo update-rc.d emonPiLCD defaults

echo 'emonPi I2C LCD installed...please reboot to take effect'

echo 'After reboot attempt to search for LCD I2C address: $sudo i2cdetect -y 1'
# Use port 1 for 512Mb RAM pi (rev2 B, B+ & 2) or port 0 for older 256Mb RAM pi Model B (rev1)
sudo i2cdetect -y 1

