#!/usr/bin/env python

# emonPi - Raspberrry Pi Energy Monitoring 
# Part of the OpenEnergyMonitor.org project 

# Based on http://www.pi-supply.com/pi-supply-switch-v1-1-code-examples/

# Import the modules to send commands to the system and access GPIO pins
from subprocess import call
import time
import RPi.GPIO as GPIO

#print 'start emonPi shutdown script on GPIO 16' 
 
# Define a function to run when an interrupt is called
def shutdown(pin):
    call('halt', shell=False)
 
GPIO.setmode(GPIO.BOARD) # Set pin numbering to board numbering
GPIO.setup(11, GPIO.IN) # Set up pin 11 GPIO 17 as an input
GPIO.add_event_detect(11, GPIO.RISING, callback=shutdown, bouncetime=200) # Set up an interrupt to look for button presses
 
while 1:
    time.sleep(1)
    #raw_input()

# GPIO.cleanup()
